enterpreneur_network/Articles/urls.py
from django.urls import path
from .import views
from .views import ArticleList, ArticleDetail, ContactUs, AboutUs

app_name = 'Articles'

urlpatterns = [
	path('articles/', ArticleList.as_view(), name='articles'),
	path('articles/<str:name>', views.article_category, name='article_category'),
	path('articles/<slug>/', ArticleDetail.as_view(), name = 'article-detail'),
	path('contactus/', ContactUs.as_view(), name='contact-us'),
	path('aboutus/', AboutUs.as_view(), name='about-us'),
	]

enterpreneur_network/Events/urls.py
from django.urls import path
from .views import event_show, CalendarView, EventDetailView, homepage, send_mail_view

app_name = 'Events'

urlpatterns = [
	path('startup-events/', event_show, name='startup-events'),
	path('startup-events/<slug>/', EventDetailView.as_view(), name = 'startup-event-detail'),
	path('calendar/', CalendarView, name='calendar'),
	path('', homepage, name='homepage'),
	path('send_email/<int:event_id>', send_mail_view, name='send_email'),
	]


enterpreneur_network/enterpreneur_network/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')), 
    path(
      'admin/password_reset/',
       auth_views.PasswordResetView.as_view(),
       name='admin_password_reset',
     ),
    path(
         'admin/password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done',
     ),
    path(
         'reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm',
     ),
    path(
         'reset/done/',
         auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete',
     ),

    path('',include('Articles.urls', namespace='Articles')),
    path('',include('Events.urls', namespace='Events')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



# <appname>/templates/admin/my_custom_index.html

admin.site.site_header = "Enterpreneur Network Administration"
admin.site.site_title = "Enterpreneur Network Admin"
admin.site.index_title = "Welcome to Admin Page"


enterpreneur_network/Events/models.py
from django.db import models
from django.contrib.auth.models import User	
from django.utils.timezone import now
from datetime import date
from django.core.exceptions import ValidationError
from django.shortcuts import reverse
from django.conf import settings


class Venue(models.Model):
    name = models.CharField('Venue Name', max_length=120)
    address = models.CharField(max_length=300)
    zip_code = models.CharField('Zip/Post Code', max_length=12,blank=True, null=True)

    VENUE_STATUS = (
		('on', 'Online'),
		('os', 'Onsite'),
		)
    venue_status_label = models.CharField(
		max_length=2,
		choices=VENUE_STATUS,
		default='os',
		help_text='Choose Venue either ONLINE or ONSITE',
		)


    class Meta:
        ordering = ['name']

    def check_status_venue(self):
    	if self.venue_status_label == 'on':
    		print("Trueeee")
    		return True
    	else:
    		return False
 
    def __str__(self):
        return self.name
 
 
class RegisteredUser(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        ordering = ['user']

    def __str__(self):
        return self.user.username


class Organizer(models.Model):
	name = models.CharField('Organizer Name', max_length=120)
	phone = models.CharField('Contact Phone', max_length=20)
	email_address = models.EmailField('Organizer Email')
	website = models.URLField('Web Address',blank=True, null=True)
	organizer_picture = models.ImageField(help_text="Add image of organizer")

	class Meta:
		ordering = ['name']

	def __str__(self):
		return self.name


class Category(models.Model):
    category_title = models.CharField(max_length=100, help_text="Add category of event")

    class Meta:
        ordering = ['category_title']

    def __str__(self):
        return self.category_title


class Event(models.Model):
	name = models.CharField('Event Name', max_length=120)
	day = models.DateField("Day of Event",default=now)
	start_time = models.TimeField("Starting Time",default=now)
	end_time = models.TimeField("Ending Time",default=now)
	picture = models.ImageField(help_text="Add picture related to event")
	description = models.TextField('Event Description')
	featured = models.BooleanField(default = False)
	categories = models.ManyToManyField(Category)
	cost = models.IntegerField(help_text="Add cost of event in case of free, write 0")
	venue = models.ForeignKey(Venue, on_delete=models.SET_NULL,null=True)
	event_manager = models.ManyToManyField(Organizer,blank =False)
	attendees = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True)
	slug = models.SlugField()
	EVENT_STATUS = (
		('o', 'On Time'),
		('d', 'Delayed'),
		('c', 'Completed'),
		)

	Event_Show = (
        ('e', 'Enable Event'),
        ('d', 'Disable Event'),
    )

	label = models.CharField(
		max_length=1,
		choices=EVENT_STATUS,
		default='o',
		help_text='Choose Event Status from here',
		)
	Event_Show_Status = models.CharField(max_length=1,choices=Event_Show,default='e',help_text='Either ENABLE and DISABLE your event')

	def get_absolute_url(self):
		return reverse('Events:startup-event-detail', kwargs = {'slug':self.slug})

	class Meta:
		ordering = ['-day']

	def clean(self):
		if self.end_time <= self.start_time:
			raise ValidationError('Ending times must after starting times')
		
	def __str__(self):
		return self.name

class Slides(models.Model):
	pic = models.ImageField(default=True)

class YoutubeUrl(models.Model):
	url = models.URLField(help_text="Enter Youtube Url")

enterpreneur_network/Events/forms.py
from django import forms
# from future import unicode_literals
from django.forms.widgets import DateInput
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime

class EventSearch(forms.Form):
	date = forms.DateField(input_formats=['%m-%Y'],
		widget=forms.DateInput(attrs={'id':'datepicker','readonly':'readonly','class':'date-own form-control',
			'style':'width: 300px',}
			,format='%m/%Y'))


class WebinarMailForm(forms.Form):
	Subject = forms.CharField(required=True)
	Content = forms.CharField(widget=forms.Textarea,required=True)

'''
{% extends "admin/app_index.html" %}
{% block content %}

<h3>Total Attendees: {{total_attendees}}</h3>
<form action="{% url 'admin:send_email' event_id=event_id %}" method='post'>  
	{% csrf_token %}
	{% for field in form %}
	<div class="form-group">
		{{field.errors}}
		{{field}}
		{{field.label_tag}}
	</div>
	{% endfor %}
	<input type="submit" value="send mail">
</form>

{% endblock %}'''

enterpreneur_network/Events/views.py
# from urllib.parse import quote_plus
from requests.utils import requote_uri
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import (ListView,DetailView,View)
from Events.models import Event,Slides,YoutubeUrl
from Articles.models import Article
# import datetime
from django.core.exceptions import ObjectDoesNotExist
from Events.forms import EventSearch
from django.http import HttpResponse
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from datetime import datetime, timedelta, date
from django.contrib.auth.decorators import login_required
# from django.views import generic
from django.utils.safestring import mark_safe
from .models import *
from .utils import Calendar
import calendar
from django.contrib import messages
from django.conf import settings
from django.contrib import admin
from django.core.mail import send_mail, BadHeaderError
from Events.forms import WebinarMailForm

def homepage(request):
	featured = Article.objects.filter(featured='True', status__exact='p').order_by('-timestamp')[0:3]
	latest = Article.objects.filter(status__exact='p').order_by('-timestamp')[0:3]
	month_event = Event.objects.filter( Event_Show_Status__exact='e',label='o').order_by('day')[0:2]
	event_one = month_event[0]
	event_two = month_event[1]
	slide_current = Slides.objects.all()[0]
	slides= Slides.objects.all()[1:5]
	Youtube = YoutubeUrl.objects.all()[0]
	print("YoutubeUrl",Youtube)

	context = {
		'featured':featured,
		'latest' :latest,
		'event_one': event_one,
		'event_two':event_two,
		'slide_current':slide_current,
		'slides':slides,
		'Youtube':Youtube
	}
	return render(request,'Events/Homepage.html',context)


def event_show(request):
	form = EventSearch()
	date = datetime.now()
	month_event = Event.objects.filter(day__year=date.year, day__month=date.month, 
		Event_Show_Status__exact='e',label='o').order_by('day')
	share_string = month_event
	if request.method == 'POST':
		form = EventSearch(request.POST)
		if form.is_valid():
			date = form.cleaned_data['date']
			month_event = Event.objects.filter(day__year=date.year, day__month=date.month,
				Event_Show_Status__exact='e',label='o').order_by('day')
			share_string = month_event
	return render(request,'Events/Event_list.html',{'form':form,'month_event':month_event,'date':date,'share_string':share_string})


class EventDetailView(DetailView):
	model = Event
	template_name = 'Events/Event_detail.html'
	context_object_name = 'event'

	
	def post(self, request, *args, **kwargs):
		if self.request.user.is_authenticated:
			event = get_object_or_404(Event , slug = self.kwargs.get('slug'))
			name = request.user.pk
			list_of_attendess = event.attendees.all()
			print('list_of_attendess',list_of_attendess)
			if request.user in list_of_attendess:
				messages.info(request,"You are already registered")
				return redirect("Events:startup-event-detail" , slug = self.kwargs.get('slug'))
			else:
				event.attendees.add(name) #takes pk as arg (ManyToManyField)
				messages.info(request,"Thanks for registration")
				return redirect("Events:startup-event-detail" , slug = self.kwargs.get('slug'))
		else:
			messages.info(request,"login required")
			return redirect("/accounts/login/")

	
		




def CalendarView(request):
	events = Event.objects.all()
	# d = get_date(request.GET.get('day', None))
	d = get_date(request.GET.get('month', None))
	cal = Calendar(d.year, d.month)
	html_cal = cal.formatmonth(withyear=True)
	print("html_calllll", mark_safe(html_cal))
	context = {'events':events,'calendar':mark_safe(html_cal),'prev_month':prev_month(d),'next_month':next_month(d)}
	return render(request,'Events/cal.html',context)


def get_date(req_month):
    if req_month:
        year, month = (int(x) for x in req_month.split('-'))
        return date(year, month, day=1)
    return datetime.today()

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month


def send_mail_view(request,event_id):
		if request.user.is_superuser:
			header = admin.site.site_header
			event_id = event_id
			event = get_object_or_404(Event , pk = event_id)
			list_of_attendess = event.attendees.all()
			form = WebinarMailForm()
			message = ''
			if request.method == 'POST':
				form = WebinarMailForm(request.POST)
				if form.is_valid():
					subject = form.cleaned_data['Subject']
					content = form.cleaned_data['Content']
					event = get_object_or_404(Event , pk = event_id)
					name = request.user.pk
					list_of_attendess = event.attendees.all()
					emails = []
					for user in list_of_attendess:
						emails.append(user.email)
					try:
						message = "Sent Successfully"
						send_mail(subject,content,settings.EMAIL_HOST_USER,emails,fail_silently=False)
					except BadHeaderError:
						return HttpResponse('Invalid header found.')
			return render(request,'Events/send_email.html', {'form':form,'event_id':event_id,'total_attendees':len(list_of_attendess),'header':header,'message':message} )
		else:
			raise Http404("Only admin can view this page")


# class ContactForm(View):
# 	form_class = ContactForm
# 	template_name = 'Events/ContactUs.html'

# 	def get(self,request):
# 		pass

# 	def post(self,request):
# 		pass

enterpreneur_network/templates/Events/Event_List.html
{% extends 'generic_base.html' %}

{% block content %}

<style>
hr { 
    display: block;
    margin-top: 0.5em;
    margin-bottom: 0.5em;
    margin-left: auto;
    margin-right: auto;
    border-style: inset;
    border-width: 3.5px;
    
} 
</style>

<!-- Image start -->
<div class="view" style="background-image: url('https://enews.wvu.edu/files/557d673d-9bd6-4f23-bee9-0a22696522dd/1200x?cb=1539112475'); background-repeat: no-repeat; background-size: cover;">

  <!-- Mask & flexbox options-->
  <div class="mask rgba-black-light d-flex justify-content-center align-items-center">
    <!-- Content -->
    <div class="text-center white-text mx-5 wow fadeIn">
        <h1 class="mb-4" style="font-weight: 700; font-family: 'Calistoga', cursive;">
          <strong>STARTUP EVENTS</strong>
        </h1>
        <h5 class="mb-4 d-none d-md-block" style="font-weight: 500;">
          <strong>Great content to learn you about enterpreneurship.</strong>
        </h5>
    </div>
    <!-- Content -->
  </div>
  <!-- Mask & flexbox options-->
</div>
<!-- Image end -->
  
<!-- form start|event search -->
<div class="container">
  <form action="{% url 'Events:startup-events' %}" method="post">
    {% csrf_token %}
    <div class='row'>
      <div class='input-group mb-3'>
        {% for field in form %}
        <div class="form-group row mx-5 mt-4">
          <div class="col-sm-7">
            <!-- input -->
            {{field}} <br>
            {% if field.help_text %}
              <small style="color: grey">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
              <p style="color: red">{{ error }}</p>
            {% endfor %}
          </div>
        </div>
        {% endfor %}
        <!-- Button -->
        <div class="input-group-append">
          <button type="submit" class="btn btn-info">Search</button>
        </div>
      </div>
    </div>
  </form>
</div>
<!-- form end -->


{% comment %}
{% if date %}
  year {{date|date:"F"}} {{date|date:"Y"}}
{% endif %}
<br>

{% if month_event %}
  <ul>
    {% for event in month_event %}
      <li>
        <h4>{{event}}</h4>
          Day{{event.day|date:"l"}} <br>
          Month {{event.day|date:"F"}}  <br>
          Date {{event.day|date:"d"}}  <br>
          Year{{event.day|date:"Y"}}  <br>
          Label : {{event.get_label_display}}
          <a href="{{event.get_absolute_url}}">Event Detail</a>
      </li>
    {% endfor %}
</ul>
{% elif date %}
     <h1>No event </h1>
{% endif %}
</div>
{% endcomment %}

<!-- Card start| Year -->
<div class="container">
  {% if date %}
    <div class="my-4 mt-5">
          <p class="date-full">
            <h1 class="text-info" style="text-align: center;">{{date|date:"F"}} {{date|date:"Y"}}</h1>        
          </p>
          <hr>
    </div>
  {% endif %}
</div>
<!-- Card end -->

<div class="container">
  {% if month_event %}
    {% for event in month_event %}
      <!-- Card starts from here -->
      <div class="container">
        <div class="row text-center">
          <div class="col-sm-12 col-md-4">
            <div class="my-4">
              <p class="date-full ">
                <h1 class="text-info">{{event.day|date:"d"}}</h1>
                <h5 class="date-month ">{{event.day|date:"F"}} | {{event.day|date:"Y"}}</h5>
              </p>
              <h3 class="day text-black-50 font-weight-light">
                {{event.day|date:"l"}}
              </h3>
            </div>
          </div>

          <div class="col-sm-12 col-md-4">
            <div class="my-4">
              <h4 class="text-dark head-text text-uppercase font-weight-bolder">
                <!-- event title -->
                {{event}}
              </h4>
              <h6 class="text-black-50 head-text-lead">
                <!-- event label -->
                {{event.get_label_display}}
               
              </h6>
              <div class="icons-container row">
                <!-- icons -->
                <div class="mx-auto ">
                                <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri}}" target="_blank">
                                    <i class="fab fa-facebook-f text-info"></i></a>
                                <a href="https://twitter.com/home?status={{event.description|urlencode}}%20{{ request.build_absolute_uri}}"  target="_blank">
                                    <i class="fab fa-twitter text-info"></i></a>
                                <a href="https://www.linkedin.com/sharing/share-offsite/?url={{ request.build_absolute_uri}}&title={{event.title}}&summary={{event.description|urlencode}}&source={{ request.build_absolute_uri}}"  target="_blank">
                                    <i class="fab fa-linkedin-in text-info"></i></a>
                                
                </div>
              </div>
            </div>
          </div>

          <div class="col-sm-12 col-md-4">
            <a class="btn btn-info m-5" href="{{event.get_absolute_url}}">View Details</a>
          </div>
        </div>    
      </div>
      <!-- Cards end -->
    {% endfor %}
  {% elif date %}
    <h1 class="text-black-50 font-weight-light" style="text-align: center;">No Event</h1>
  {% endif %}
</div>


<script >
  
$('.date-own').datepicker({
    minViewMode: 1,
    format: 'mm-yyyy',
    orientation: "top left"
  });
</script>

{% endblock %}





enterpreneur_network/templates/Events/Event_detail.html
{% extends 'generic_base.html' %}

{% block content %}

<style>
hr { 
    display: block;
    margin-top: 0.5em;
    margin-bottom: 0.5em;
    margin-left: auto;
    margin-right: auto;
    border-style: inset;
    border-width: 0.5px;
    border-color:#5bc0de;
} 
</style>

<main class="mt-5 pt-5">
  <!-- messages -->
  <div class="container">
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{message}}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      {% endfor %}
    {% endif %}
  </div>
  <div class="container">
    <section class="mt-4">
      <!--Grid row-->
      <div class="row">
        <!--Grid column-->
        <div class="col-md-8 mb-4">
          <!--Featured Image-->
          <div class="card mb-4 wow fadeIn">
            <img src="{{event.picture.url}}" class="img-fluid" alt="" style="height: 20rem;width:50rem;">
          </div>
          <div class="wow fadeIn">
            <!--Section heading-->
            <h2 class="h1 mb-9 mt-4" style="text-align: left; font-weight: 1000;">
              {% if event.venue.check_status_venue %}
                  WEBINAR - {{event.name}}
              {% else %}
                  EVENT - {{event.name}}
              {% endif %}
            </h2>

            <!--Section description-->
            <h5 class="mt-4" style="text-align: left; font-weight: 1000;"> Event Description :</h5>
            <p class="mt-4 text-black-50 font-weight-light" style="text-align: left;">{{event.description}} </p>
            <div class="container mt-4">
              <!-- Registration form|button -->
              <form action="{{event.get_absolute_url}}" method="post">
                {% csrf_token %}
                  <button type="submit" class="btn btn-outline-info btn-lg btn-block">Register Now</button>
              </form>
            </div>
          </div>
        </div>

        <!--Grid column-->
        <div class="col-md-4 mb-4">
          <!--Card : Dynamic content wrapper-->
          <div class="card mb-4 text-center wow fadeIn">
            <!--Card content-->
            <div class="card-body">
              <!-- Date -->
              <h5><i class="far fa-calendar-alt text-info"></i><b> DATE</b></h5>
              <div class="grey-text">{{event.day}}</div>
                <hr>
                <!-- Time -->
                <h5><i class="far fa-clock text-info" ></i><b> TIME</b></h5>
                <div class="grey-text">START TIME : {{event.start_time}} <br>
                  END TIME : {{event.end_time}}
                </div>
                <hr>
                <!-- Cost -->
                <h5><i class="fas fa-hand-holding-usd text-info"></i><b> COST</b></h5>
                <div class="grey-text">
                  {% if event.cost == 0 %}
                    Free
                  {% else %}
                    {{event.cost}}
                  {% endif %}
                </div>
                <hr>
                <!-- Label -->
                <h5><i class="fas fa-tags text-info"></i><b> LABEL</b></h5>
                <div class="grey-text">{{event.get_label_display}}</div>
                <hr>
                <!-- Category -->
                <h5><i class="fas fa-folder text-info"></i><b> CATEGORY</b></h5>
                  <div class="grey-text">
                     <br/>{% for category in event.categories.all %}{{category}}<br/>{% endfor %}
                  </div>
            </div>
          </div>
          <!--/.Card : Dynamic content wrapper-->

          <!--Card : Dynamic content wrapper-->
          <div class="card mb-4 text-center wow fadeIn">
            <div class="card-header"><h4><b>VENUE</b></h4></div>
              <!--Card content-->
              <div class="card-body">
                <!-- Venue -->
                <h5><b> VENUE NAME </b></h5>
                <div class="grey-text">{{event.venue.name}}</div> <hr>
                   <h5><i class="fas fa-map-marker-alt text-info"></i><b> LOCATION</b></h5>
                <div class="grey-text">{{event.venue.address}}</div>
              </div>
          </div>
          <!--/.Card : Dynamic content wrapper-->

          <!--Card : Dynamic content wrapper-->
          <div class="card mb-4 text-center wow fadeIn">
              <div class="card-header"><h4><b>ORGANIZERS</b></h4></div>
              <!--Card content-->
              <div class="card-body">
                {% for organizer in event.event_manager.all %}
                  <div class="grey-text">
                    <div class="media">
                      <img class="d-flex ml-4 mr-4 mx-auto" src="{{organizer.organizer_picture.url}}" alt="Generic placeholder image"
                      style="height: 10rem;width: 100%;">
                    </div>
                    NAME {{organizer.name}} <br>
                    PHONE {{organizer.phone}} <br>
                    EMAIL {{organizer.email_address}} <br>
                    {% if website %} WEBSITE {{organizer.website}} {% endif %} <br>
                  </div>
                {% endfor %}
              </div>
          </div>
        </div>
      </div>
    </section>
  </div>
  
{% comment %}
<img src="{{event.picture.url}}" class="img-responsive" style="height: 400px"> <br>
{% if event.venue.check_status_venue %}
 	Webinar
{% else %}
 	Event
{% endif %}
<h1>Name: {{event.name}}</h1> <br>
<h3>Event Description: <br> {{event.description}}</h3> <br>

<h2> Schedule </h2>
<h5>Date: {{event.day}}</h5>
<h5>Start Time: {{event.start_time}} </h5>
<h5>End Time: {{event.end_time}}</h5>

<h2> Cost </h2>
{% if event.cost == 0 %}
	Free
{% else %}
	{{event.cost}}
{% endif %}

<h2> Label: {{event.get_label_display}} </h2>
<h2>Category: <br/>{% for category in event.categories.all %}{{category}}<br/>{% endfor %}</h2>

<h2> Location </h2>
{{event.venue.get_venue_status_label_display}}
{{event.venue.name}} </br>
{% if event.venue.address %}
{{event.venue.address}}
{% endif %}

<h2> Organizer </h2>
{% for organizer in event.event_manager.all %}
	<img src="{{organizer.organizer_picture.url}}" class="img-responsive" style="height: 100px"> <br>
	Name: {{organizer.name}} </br>
	Phone: {{organizer.phone}} </br>
	Email: {{organizer.email_address}} </br>
	{% if website %} Website: {{organizer.website}} {% endif %} </br>
{% endfor %}

<form action="{{event.get_absolute_url}}" method="post">
	{% csrf_token %}
	<input type="submit" value="Register">
</form>

</div>
{% endcomment %}

</main>

{% endblock %}

enterpreneur_network/templates/Events/cal.html
{% extends 'generic_base.html' %}

{% block content %}


<main class="mt-5 pt-5">
{{calendar}}
  <div class="clear-fix">
  <a class="btn btn-info left" href="{% url 'Events:calendar' %}?{{ prev_month }}"> Previous Month </a>
  <a class="btn btn-info right" href="{% url 'Events:calendar' %}?{{ next_month }}"> Next Month </a>
</div>


    


</main>
 <script>
// When the user clicks on div, open the popup
function myFunction() {
  var popup = document.getElementById("myPopup");
  popup.classList.toggle("show");
}
</script>

{% endblock %}

{% block footer %}


{% endblock %}

enterpreneur_network/templates/Events/send_email.html

{% extends "admin/app_index.html" %}
{% load i18n %}

{% block title %}{{ title }} | {% trans 'Webinar Email' %}{% endblock %}
{% block branding %}
<h1 id="site-name">{% trans header %}</h1>
{% endblock %}
{% block content %}

<fieldset class="module aligned wide extrapretty">
    <h2>Email Webinar link to Attendees <a href="{% url 'admin:Events_event_changelist' %}" style="color:white">Event List</a>
    <a href="{% url 'admin:Events_event_change' object_id=event_id %}" style="color:white"> Back</a> </h2> 
    </fieldset>
<h3>Total Attendees: {{total_attendees}}</h3>
<form action="{% url 'Events:send_email' event_id=event_id %}" method='post'>  
	{% csrf_token %}
	{% for field in form %}
	<div class="form-group">
		{{field.label_tag}}
		{{field.errors}}
		{{field}}
		
	</div>
	{% endfor %}
	<input type="submit" value="send mail">
</form>
{{message}}

{% endblock %}