enterpreneur_network/Articles/urls.py
from django.urls import path
from .import views
from .views import ArticleList, ArticleDetail, ContactUs, AboutUs

app_name = 'Articles'

urlpatterns = [
	path('articles/', ArticleList.as_view(), name='articles'),
	path('articles/<str:name>', views.article_category, name='article_category'),
	path('articles/<slug>/', ArticleDetail.as_view(), name = 'article-detail'),
	path('contactus/', ContactUs.as_view(), name='contact-us'),
	path('aboutus/', AboutUs.as_view(), name='about-us'),
	]

enterpreneur_network/Events/urls.py
from django.urls import path
from .views import event_show, CalendarView, EventDetailView, homepage, send_mail_view

app_name = 'Events'

urlpatterns = [
	path('startup-events/', event_show, name='startup-events'),
	path('startup-events/<slug>/', EventDetailView.as_view(), name = 'startup-event-detail'),
	path('calendar/', CalendarView, name='calendar'),
	path('', homepage, name='homepage'),
	path('send_email/<int:event_id>', send_mail_view, name='send_email'),
	]


enterpreneur_network/enterpreneur_network/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')), 
    path(
      'admin/password_reset/',
       auth_views.PasswordResetView.as_view(),
       name='admin_password_reset',
     ),
    path(
         'admin/password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done',
     ),
    path(
         'reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm',
     ),
    path(
         'reset/done/',
         auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete',
     ),

    path('',include('Articles.urls', namespace='Articles')),
    path('',include('Events.urls', namespace='Events')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



# <appname>/templates/admin/my_custom_index.html

admin.site.site_header = "Enterpreneur Network Administration"
admin.site.site_title = "Enterpreneur Network Admin"
admin.site.index_title = "Welcome to Admin Page"


enterpreneur_network/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>LeanGhana</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script> -->
   <!--  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script> -->
    
    <!-- Datepicker -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>

  {% block style %}
  {% endblock %}

</head>

<body>
  {% block navbar %}
  <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="#" target="_blank">
        <strong class="blue-text">LeanGhana</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link waves-effect" href="">HOME
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="">
               ABOUT US
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'Articles:articles' %}">
               ARTICLES & CONTENT
            </a>
          </li>
           <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
           PROGRAMS & EVENTS
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'Events:calendar' %}">EVENT CALENDER</a>
          <a class="dropdown-item" href="{% url 'Events:startup-events' %}">UPCOMING EVENTS</a>
          
      </li>
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_logout'%}">
                <span class="clearfix d-none d-sm-inline-block"> Logout </span>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_login'%}">
                <span class="clearfix d-none d-sm-inline-block"> Login </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_signup'%}">
                <span class="clearfix d-none d-sm-inline-block"> Signup </span>
            </a>
          </li>
          {% endif %}

          <li class="nav-item">
            <a href="#" class="nav-link border border-light rounded waves-effect"
              target="_blank">
              GET STARTED
            </a>
          </li>
        </ul>

      </div>

    </div>
  </nav>
  {% endblock %}

<div class="mt-5 pt-4">
  {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
      {{message}}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endfor %}
  {% endif %}
</div>


  {% block content %}
  {% endblock %}

  {% block footer %}
  <!--Footer-->
  <footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <!--Call to action-->
    <div class="pt-4">
      
    </div>
    <!--/.Call to action-->

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="" target="_blank"> LeanGhana.com </a>
    </div>
    <!--/.Copyright-->

  </footer>
  {% endblock %}
  <!--/.Footer-->

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <!-- Initializations -->
  
</body>

</html>

enterpreneur_network/templates/generic_base.html
{% load static %}
<!DOCTYPE html>
<html>
{% load static %}
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>LEANGHANA</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/about_us.css' %}" rel="stylesheet">
    <link href="{% static 'css/cal.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Calistoga&display=swap" rel="stylesheet">
  
    <link rel='stylesheet' type='text/css' media='screen' href="{% static 'css/main.css' %}">
    <link rel='stylesheet' type='text/css' media='screen' href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.8.10/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
        integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.8.10/js/bootstrap.min.js"></script>
    <!-- Datepicker -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>

{% block style %}
{% endblock %}
</head>

<body>
  <!-- Navbar start  -->
  {% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light fixed-top">
        <div class="container">
            <a class="navbar-brand" href="{% url 'Events:homepage' %}">
                <h3> LeanGhana</h3>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto left__navList">
                    <li class="nav-item ">
                        <a class="nav-link text-uppercase" href="{% url 'Events:homepage' %}">Home <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-uppercase" href="{% url 'Articles:about-us' %}">About Us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-uppercase" href="{% url 'Articles:articles' %}">Articles & Contents</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        PROGRAMS & EVENTS
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                              <a class="dropdown-item" href="{% url 'Events:calendar' %}">EVENT CALENDER</a>
                              <a class="dropdown-item" href="{% url 'Events:startup-events' %}">UPCOMING EVENTS
                              </a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-uppercase"
                            href="{% url 'account_signup'%}">Member</a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto ">
                    {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link " href="{% url 'account_logout'%}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link " href="{% url 'account_login'%}">Sign In</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link px-3 menu-button btn btn-info"
                            href="{% url 'account_signup'%}">Get Started</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="modal fade" tabindex="-1" role="dialog" id="modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>


    
  {% endblock %}
  <!-- Navbar end -->

  <!-- Content start -->
  {% block content %}
  {% endblock %}
  <!-- Content end -->

  <!-- Pagination Start -->
  {% block pagination %}
    <nav class="d-flex justify-content-center wow fadeIn">
        {% if is_paginated %}
        <ul class="pagination pg-blue">
          <!--Arrow left-->
          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="{{ request.path }}?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}
          <li class="page-item active">
            <a class="page-link" href="#"> Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
              <span class="sr-only">(current)</span>
            </a>
          </li>
          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="{{ request.path }}?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
        {% endif %}
    </nav>
  {% endblock %} 
  <!-- Pagination end -->

  <!-- Footer start -->
  {% block footer %}
    <footer class="footer mt-5">
        <section class="container footer__main">
            <div class="row">
                <div class="col-sm-6 col-xl-3">
                    <h4 class="text-underline"> Company </h4>
                    <a href="/about" class="footer-anchor"> About Us </a>
                    <a href="/careers" class="footer-anchor"> Careers </a>
                    <a href="{% url 'Articles:contact-us' %}" class="footer-anchor"> Contact Us </a>
                </div>
                <div class="col-sm-6 col-xl-3">
                    <h4> Solutions </h4>
                    <a href="/founders/start" class="footer-anchor"> Start a Company </a>
                    <a href="/founders/grow" class="footer-anchor"> Grow Your Startup </a>
                    <a href="/founders/raise" class="footer-anchor"> Raise Capital </a>
                </div>
                <div class="col-sm-6 col-xl-3">
                    <h4> Products </h4>
                    <a href="/launch?utm_source=marketing-gust.com&utm_medium=footer&utm_campaign=core-caas"
                        target="_blank" class="footer-anchor"> Gust Launch </a>
                    <a href="https://cofounders.gust.com/" target="_blank" class="footer-anchor">
                     Co-Founder Equity
                        Split
                    </a>
                    <a href="/investors" class="footer-anchor"> Gust for Investors </a>
                    <a href="https://gust.com/accelerators" class="footer-anchor"> Gust for Accelerators </a>
                </div>
                <div class="col-sm-6 col-xl-3">
                    <h4> Resources </h4>
                    <a href="{% url 'Articles:articles' %}" class="footer-anchor"> Blog </a>
                    <a href="https://gust.helpscoutdocs.com/" target="_blank" class="footer-anchor"> Support </a>
                </div>
            </div>
        </section>

        <section class="footer__slim container text-center">
            <div class="footer__slim__left">
                <a href="/tos" class="footer-anchor mx-1"> Terms of Service </a>
                <a href="/privacy-policy" class="footer-anchor mx-1"> Privacy Policy </a>
                <span class="footer-text mx-1"> © LeanGhana 2019 </span>
            </div>
            <div class="footer__slim__right mx-auto mx-md-0">
                <a href="https://twitter.com/gustly" target="_blank" class="btn--social mx-auto text-dark">
                    <i class="fab fa-twitter"></i>
                </a>
                <a href="https://www.facebook.com/pages/Gust/246116808757618" target="_blank"
                    class="text-dark mx-auto btn--social">
                    <i class="fab fa-facebook-f"></i>
                </a>
            </div>
        </section>

    </footer>
  {% endblock %}
  <!-- Footer end -->

<!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/timer.js' %}"></script>

<script>
    window.onscroll = () => {
        const navibar = document.querySelector("nav")
        if (this.scrollY <= 100) {
            navibar.className = "navbar navbar-expand-lg navbar-light bg-nav fixed-top"
        }
        else {
            navibar.className = "navbar navbar-expand-lg navbar-light bg-dark text-nav fixed-top"
        }
    }
</script>
</body>
</html>