enterpreneur_network/Articles/urls.py
from django.urls import path
from .import views
from .views import ArticleList, ArticleDetail, ContactUs, AboutUs

app_name = 'Articles'

urlpatterns = [
	path('articles/', ArticleList.as_view(), name='articles'),
	path('articles/<str:name>', views.article_category, name='article_category'),
	path('articles/<slug>/', ArticleDetail.as_view(), name = 'article-detail'),
	path('contactus/', ContactUs.as_view(), name='contact-us'),
	path('aboutus/', AboutUs.as_view(), name='about-us'),
	]

enterpreneur_network/Events/urls.py
from django.urls import path
from .views import event_show, CalendarView, EventDetailView, homepage, send_mail_view

app_name = 'Events'

urlpatterns = [
	path('startup-events/', event_show, name='startup-events'),
	path('startup-events/<slug>/', EventDetailView.as_view(), name = 'startup-event-detail'),
	path('calendar/', CalendarView, name='calendar'),
	path('', homepage, name='homepage'),
	path('send_email/<int:event_id>', send_mail_view, name='send_email'),
	]


enterpreneur_network/enterpreneur_network/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')), 
    path(
      'admin/password_reset/',
       auth_views.PasswordResetView.as_view(),
       name='admin_password_reset',
     ),
    path(
         'admin/password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done',
     ),
    path(
         'reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm',
     ),
    path(
         'reset/done/',
         auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete',
     ),

    path('',include('Articles.urls', namespace='Articles')),
    path('',include('Events.urls', namespace='Events')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



# <appname>/templates/admin/my_custom_index.html

admin.site.site_header = "Enterpreneur Network Administration"
admin.site.site_title = "Enterpreneur Network Admin"
admin.site.index_title = "Welcome to Admin Page"


enterpreneur_network/Articles/models.py
from django.db import models
from django.contrib.auth.models import User	
from ckeditor_uploader.fields import RichTextUploadingField
from django.shortcuts import reverse
from django.conf import settings

class Author(models.Model):
    author_name = models.CharField(max_length=250)
    profile_picture = models.ImageField(help_text='Add picture of author')
    about_author = models.CharField(max_length=1000, help_text='Add something about author')
    website = models.URLField(max_length=250, blank=True, null=True, help_text="Add URL of your website")
    linkedin = models.URLField(max_length=250, blank=True, null=True, help_text="Add URL of your linkedin account")
    facebook = models.URLField(max_length=250, blank=True, null=True, help_text="Add URL of your FB account")
    insta = models.URLField(max_length=250, blank=True, null=True, help_text="Add URL of your insta account")
    others = models.URLField(max_length=250, blank=True, null=True,  help_text="Add other URL (e.g github account etc)")

    class Meta:
        ordering = ['author_name']

    def __str__(self):
        return self.author_name


class Category(models.Model):
    category_title = models.CharField(max_length=100, help_text="Add category of article")

    class Meta:
        ordering = ['category_title']

    def __str__(self):
        return self.category_title


class Article(models.Model):
    title = models.CharField(max_length=100)
    #overview = models.TextField()
    thumbnail = models.ImageField(help_text='Add image related to your blog')
    categories = models.ManyToManyField(Category)
    content = RichTextUploadingField()
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
   
    ARTICLE_STATUS = (
        ('d', 'Draft'),
        ('p', 'Published'),
        ('w', 'Withdrawn'),
    )
    featured = models.BooleanField()
    status = models.CharField(
        max_length=1,
        choices=ARTICLE_STATUS,
        default='d',
        help_text='Status of articles',
    )

    slug = models.SlugField()

    def get_absolute_url(self):
        return reverse('Articles:article-detail', kwargs = {'slug':self.slug})

    class Meta:
        ordering = ['-timestamp']

    def __str__(self):
        return self.title


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    content = models.TextField('Comment')
    post = models.ForeignKey(
        Article, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-timestamp']

    def __str__(self):
        return self.user.username



enterpreneur_network/Articles/forms.py
from django import forms

class ContactForm(forms.Form):
	name = forms.CharField(required=True,widget=forms.TextInput(attrs={'class':'form-control'}))
	email = forms.EmailField(required=True,widget=forms.TextInput(attrs={'class':'form-control'}))
	message = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control md-textarea'}),required=True)

enterpreneur_network/Articles/views.py
from django.shortcuts import render
from django.views.generic import (ListView,DetailView,View)
from .models import Article, Category
from Articles.forms import ContactForm
from django.core.mail import send_mail, BadHeaderError
from django.conf import settings
from django.views.generic.base import TemplateView

class ArticleList(ListView):
	model = Article
	paginate_by = 10
	template_name = 'Articles/Articles_list.html'
	context_object_name = 'articles'

	def get_queryset(self):
		return Article.objects.filter(status__exact='p').order_by('-timestamp')

	def get_context_data(self,**kwargs):
		context = super(ArticleList,self).get_context_data(**kwargs) #returns a dictionary of context
		new_context_objects = {'Categories':Category.objects.all()}
		context.update(new_context_objects)
		return context 

def article_category(request,name):
	Articles = Article.objects.filter(categories__category_title=name, status__exact='p')
	context = {'Articles':Articles,'name':name}
	return render(request , 'Articles/articles_category.html',context)

class ArticleDetail(DetailView):
	model = Article
	template_name = 'Articles/Articles_detail.html'
	context_object_name = 'article_detail'

	def get_context_data(self,**kwargs):
		context = super(ArticleDetail,self).get_context_data(**kwargs)
		m = self.kwargs.get('slug')
		for i in Article.objects.filter(slug = m):
			a = i.categories.all()[0]
		q = Article.objects.filter(categories = a)[0:3]
		new_context = {'categories':q}
		context.update(new_context)
		return context


class ContactUs(View):
	form_class = ContactForm
	template_name = 'Articles/contact_us.html'

	def get(self,request):
		form = self.form_class()
		return render (request,self.template_name,{'form':form})

	def post(self,request):
		form = self.form_class(request.POST)
		if form.is_valid():
			name = form.cleaned_data['name']
			email = form.cleaned_data['email']
			subject = 'Enterpreneur Network: Contact message from{}'.format(name)
			message = form.cleaned_data['message']
			send_mail(subject,message,email,[settings.EMAIL_HOST_USER],fail_silently=False)
			try:
				email_status = 'Thanks {} for contacting us'.format(name)
			except BadHeaderError:
				return HttpResponse('Invalid header found.')
			return render (request,self.template_name,{'form':form,'email_status':email_status})
		else:
			email_status = 'Please provide correct data'
			return render (request,self.template_name,{'form':form,'email_status':email_status})

class AboutUs(TemplateView):
	template_name = 'Articles/about_us.html'
	




enterpreneur_network/templates/Articles/Articles_detail.html
{% extends 'generic_base.html' %}

{% block style %}
<style>
	img {
		max-width: 25rem;
    max-height: 20rem;
    display: block;
    margin-left: auto;
    margin-right: auto;
      }

	/* p {
    color: #808080;
    font-family: Consolas;
    font-size:12pt;
  }*/
</style>
{% endblock %}

{% block content %}
  <!--Main layout-->
  <main class="mt-4 pt-5">
    <div class="container">
      <!--Section: Post-->
      <section class="mt-4">
        <!--Grid row-->
        <div class="row">
          <!--Grid column-->
          <div class="col-md-8 mb-4">
            <!--Featured Image start-->
            <div class="card mb-4 wow fadeIn">
              <img src="{{article_detail.thumbnail.url}}" class="img-fluid" alt="" style="height: 20rem;width:50rem;">
            </div>
            <!--Featured Image end-->

            <!--Card start|Title of article-->
            <div class="card mb-4 wow fadeIn">
              <!--Card content-->
              <div class="card-body text-center">
                <h1 style="font-weight: 700;">{{article_detail.title}}</h1>
              </div>
            </div>
            <!--Card end-->

            <!--Card start| aryticle description-->
            <div class="card mb-4 wow fadeIn">
              <!--Card content-->
              <div class="card-body">
                <p> {{article_detail.content|safe}}</p>
              </div>
            </div>
            <!--/.Card end-->

            <!--Card start|Author links-->
            <div class="card mb-4 wow fadeIn">
              <div class="card-header font-weight-bold">
                <span>About author</span>
                <span class="pull-right">
                {% if article_detail.author.facebook %}
                  <a href="{{article_detail.author.facebook}}" target="_blank">
                    <i class="fab fa-facebook-f mr-2"></i>
                  </a>
                {% endif %}
                  
                {% if article_detail.author.insta %}
                  <a href="">
                    <i class="fab fa-instagram mr-2"></i>
                  </a>
                {% endif %}
                {% if article_detail.author.linkedin %}
                  <a href="{{article_detail.author.linkedin}}" target="_blank">
                    <i class="fab fa-linkedin-in mr-2"></i>
                  </a>
                {% endif %}
                </span>
              </div>
              <!-- Card end -->

              <!--Card content| Author description-->
              <div class="card-body">
                <div class="media d-block d-md-flex mt-3">
                  <img class="d-flex mb-3 mx-auto z-depth-1" src="https://mdbootstrap.com/img/Photos/Avatars/img (30).jpg"
                    alt="Generic placeholder image" style="width: 100px;">
                  <div class="media-body text-center text-md-left ml-md-3 ml-0">
                    <!-- Author name -->
                    <h5 class="mt-0 font-weight-bold">{{article_detail.author.author_name}}
                    </h5>
                    <!-- About author -->
                    {{article_detail.author.about_author}} <hr>
                    {% if article_detail.author.website %}
                        <!-- Official website link -->
                        Official website: <a href="{{article_detail.author.website}}" target="_blank" class="text-info">{{article_detail.author.website}}</a>
                    {% endif %}

                    {% if article_detail.author.others %}
                      Others: <a href="{{article_detail.author.others}}" target="_blank" class="text-info">{{article_detail.author.others}}</a>
                    {% endif %} 
                  </div>
                </div>
              </div>
              <!-- Card content end -->
            </div>
            <!--/.Card-->
          </div>
          <!--Grid column-->

          <!--Grid column|Related Articles-->
          <div class="col-md-4 mb-4">
            <!--Card start-->
            <div class="card mb-4 wow fadeIn">
              <div class="card-header">Related articles</div>
              <div class="card-body">
                <ul class="list-unstyled">
                  {% for article in categories %}
                  <li class="media my-4">
                    <img class="d-flex mr-3" src="{{article.thumbnail.url}}" alt="Generic placeholder image"
                    style="height: 5rem;width: 5rem;">
                    <div class="media-body">
                      <a href="{{article.get_absolute_url}}">
                        <h5 class="mt-0 mb-1 font-weight-bold text-info">{{article.title}}</h5>
                      </a>
                     Author: {{article.author}} <br>
                     {{article.timestamp}}
                    </div>
                  </li>
                  {% endfor %}
                </ul>
              </div>
            </div>
            <!--/.Card end-->
          </div>
          <!--Grid column-->
        </div>
      </section>
      <!--Section: Post-->
    </div>
  </main>
  <!--Main layout-->

 {% comment %}

{% if article_detail.author.website %}
<a href="{{article_detail.author.website}}">{{article_detail.author.website}}</a>
{% endif %}

{% if article_detail.author.linkedin %}
{{article_detail.author.linkedin}}
{% endif %}

{% if article_detail.author.facebook %}
{{article_detail.author.facebook}}
{% endif %}

{% if article_detail.author.insta %}
{{article_detail.author.insta}}
{% endif %}

{% if article_detail.author.others %}
{{article_detail.author.others}}
{% endif %} {% endcomment %}

{% endblock %}


enterpreneur_network/templates/Articles/Articles_list.html
{% extends 'generic_base.html' %}

{% block style %}
<style type="text/css">
  @import url('https://fonts.googleapis.com/css?family=Calistoga&display=swap');
     @media (min-width: 800px) and (max-width: 850px) {
      .navbar:not(.top-nav-collapse) {
        background: #1C2331 !important;
      }
    }
</style>
{% endblock %}

{% block content %}
<!-- Top image start-->
<div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Others/images/93.jpg'); background-repeat: no-repeat; background-size: cover;">
    <!-- Mask & flexbox options-->
    <div class="mask rgba-black-light d-flex justify-content-center align-items-center">
      <!-- Content start -->
      <div class="text-center white-text mx-5 wow fadeIn">
        <h1 class="mb-4" style="font-weight: 700; font-family: 'Calistoga', cursive;">
          <strong>ARTICLES EXPERTS AND STORIES OF ENTERRPRENUERSHIP</strong>
        </h1>
        <h5 class="mb-4 d-none d-md-block" style="font-weight: 500;">
          <strong>Great content to learn you about enterpreneurship.</strong>
        </h5>
      </div>
      <!-- Content end -->
    </div>
    <!-- Mask & flexbox options-->
</div>
<!-- Top image end -->

<div class="container">
  <!--Navbar-->
  <nav class="navbar navbar-expand-lg navbar-light mdb-color lighten-5 mt-3 mb-5 ">
    <!-- Navbar brand -->
    <span class="navbar-brand">Categories:</span>
      <!-- Collapse button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <!-- Collapsible content -->
      <div class="collapse navbar-collapse" id="basicExampleNav">
          <!-- Category Links start -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'Articles:articles' %}">All
                <span class="sr-only">(current)</span>
            </a>
          </li>
          {% for category in Categories %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Articles:article_category' category.category_title %}">{{category}}</a>
            </li>
          {% endfor %}
        </ul>
          <!--Category Links end -->
      </div>
      <!-- Collapsible content -->
  </nav>
  <!--/.Navbar-->

  <!--Grid row-->
  <div class="row mb-4 wow fadeIn">
    {% if articles %}
      {% for article in articles %}
        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">
          <!--Card start-->
          <div class="card">
            <!--Card image start-->
              <div class="view overlay">
                <img src="{{article.thumbnail.url}}" class="card-img-top" alt="" style="width: 100%; height: 12rem;">
                <a href="{{article.get_absolute_url}}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!-- Card image end -->
              <!--Card content-->
              <div class="card-body">
                <!-- Article time -->
                <p class="card-text">{{article.timestamp}} </p>                            
                <!--Title-->
                <h6 class="card-title">{{article}}</h6>
              </div>
          </div>
          <!--Card end-->
        </div>
        <!--Grid column-->
      {% endfor %}
    {% else %}
      <h4>No articles</h4>
    {% endif %}
  </div>
  <!--Grid row-->
</div>

{% endblock %}

enterpreneur_network/templates/Articles/about_us.html
{% extends 'generic_base.html' %}

{% block content %}
<main>
<div class="ct-pageWrapper" id="ct-js-wrapper">
  <section class="company-heading intro-type" id="parallax-one">
    <div class="container">
      <div class="row product-title-info">
        <div class="col-md-12">
          <h1>About Us</h1>
        </div>
      </div>
    </div>
    <div class="parallax" id="parallax-cta" style="background-image:url(https://www.solodev.com/assets/hero/hero.jpg);"></div>
  </section>
  <section class="story-section company-sections ct-u-paddingBoth100 paddingBothHalf noTopMobilePadding" id="section">
    <div class="container text-center">
      <h2>WHAT DRIVES US</h2>
      <h3>Lorem ipsum - dolor</h3>
      <div class="col-md-8 col-md-offset-2 container">
        <div class="blue-border"></div>
        <p class="ct-u-size22 ct-u-fontWeight300 marginTop40">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sed libero vel ex maximus vulputate nec eu ligula. Vestibulum elementum nisi ut fermentum lobortis. Sed quis iaculis felis.</p>
        <!-- <a class="ct-u-marginTop60 btn btn-solodev-red btn-fullWidth-sm ct-u-size19" href="#">Learn More</a> -->
      </div>
    </div>
  </section>
  <section class="culture-section company-sections ct-u-paddingBoth100 paddingBothHalf noTopMobilePadding">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2 container">
          <h2>Etiam varius porttitor</h2>
          <h3>Vestibulum elementum nisi ut</h3>
          <p class="ct-u-size22 ct-u-fontWeight300 ct-u-marginBottom60">Lorem ipsum dolor sit amet, consectetur adipiscing elit.<br>
          Praesent sed libero vel ex maximus vulputate nec eu ligula. Vestibulum elementum nisi ut fermentum lobortis.</p>
        </div>
      </div>
      <a class="ct-u-marginTop60 btn btn-solodev-red-reversed btn-fullWidth-sm ct-u-size19" href="/careers/">Ready to Learn More?</a>
    </div>
  </section>
  <section class="customers-section company-sections ct-u-paddingBoth100 paddingBothHalf noTopMobilePadding">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2 container">
          <h2>CUSTOMERS</h2>
          <h3>Trusted by some of the world’s leading brands.</h3>
          <p class="ct-u-size22 ct-u-fontWeight300 ct-u-marginBottom60 marginTop40">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sed libero vel ex maximus vulputate nec eu ligula. Vestibulum elementum nisi ut fermentum lobortis. Sed quis iaculis felis.</p>
        </div>
        <div class="clearfix">
      </div>
    </div>
  </section>
</div>
<main>
  <div class="container ct-u-paddingTop40 ct-u-paddingBottom100">
    <div class="row">
      <div class="col-md-12 ct-content">
        <section class="clients-home">
          <div class="container">
            <div class="clients-logos text-center">
              <div class="row">
                <div class="col-md-4 client-logos-repeater">
                  <a href="/path/to/detail/zeina.html" class="Zeina"><img alt="https://www.solodev.com/assets/clients/logo-zeina.png" src="https://www.solodev.com/assets/clients/logo-zeina.png"></a>
                  <div class="logo-title">
                    <div class="displayTable">
                      <div class="displayTableCell">Zeina - 0</div>
                    </div>
                  </div>
                </div>
                <div class="col-md-4 client-logos-repeater">
                  <a href="/path/to/detail/logic.html" class="Logic"><img alt="https://www.solodev.com/assets/clients/logic.png" src="https://www.solodev.com/assets/clients/logic.png"></a>
                  <div class="logo-title">
                    <div class="displayTable">
                      <div class="displayTableCell">Logic</div>
                    </div>
                  </div>
                </div>
                <div class="col-md-4 client-logos-repeater">
                  <a href="/path/to/detail/smart.html" class="Smart"><img alt="https://www.solodev.com/assets/clients/client3.png" src="https://www.solodev.com/assets/clients/client3.png"></a>
                  <div class="logo-title">
                    <div class="displayTable">
                      <div class="displayTableCell">Smart</div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-4 client-logos-repeater">
                  <a href="/path/to/detail/softtech.html" class="Softtech"><img alt="https://www.solodev.com/assets/clients/softtech.png" src="https://www.solodev.com/assets/clients/softtech.png"></a>
                  <div class="logo-title">
                    <div class="displayTable">
                      <div class="displayTableCell">Softtech</div>
                    </div>
                  </div>
                </div>
                <div class="col-md-4 client-logos-repeater">
                  <a href="/path/to/detail/wheel.html" class="Wheel"><img alt="https://www.solodev.com/assets/clients/logo-target.png" src="https://www.solodev.com/assets/clients/logo-target.png"></a>
                  <div class="logo-title">
                    <div class="displayTable">
                      <div class="displayTableCell">Wheel</div>
                    </div>
                  </div>
                </div>
                <div class="col-md-4 client-logos-repeater">
                  <a href="/path/to/detail/3designs.html" class="3designs"><img alt="https://www.solodev.com/assets/clients/designx.png" src="https://www.solodev.com/assets/clients/designx.png"></a>
                  <div class="logo-title">
                    <div class="displayTable">
                      <div class="displayTableCell">3designs</div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-4 client-logos-repeater">
                  <a href="/path/to/detail/heart.html" class="Heart"><img alt="https://www.solodev.com/assets/clients/client7.png" src="https://www.solodev.com/assets/clients/client7.png"></a>
                  <div class="logo-title">
                    <div class="displayTable">
                      <div class="displayTableCell">Heart</div>
                    </div>
                  </div>
                </div>
                <div class="col-md-4 client-logos-repeater">
                  <a href="/path/to/detail/devtech.html" class="Devtech"><img alt="https://www.solodev.com/assets/clients/devtech.png" src="https://www.solodev.com/assets/clients/devtech.png"></a>
                  <div class="logo-title">
                    <div class="displayTable">
                      <div class="displayTableCell">Devtech</div>
                    </div>
                  </div>
                </div>
                <div class="col-md-4 client-logos-repeater">
                  <a href="/path/to/detail/chartz.html" class="Chartz"><img alt="https://www.solodev.com/assets/clients/chartz.png" src="https://www.solodev.com/assets/clients/chartz.png"></a>
                  <div class="logo-title">
                    <div class="displayTable">
                      <div class="displayTableCell">Chartz</div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  </div>
</main>




{% endblock %}

enterpreneur_network/templates/Articles/article_form.html

<style> 
        input{ 
            width:100%; 
            padding: 12px; 
            } 
</style> 

<div class="col-sm-7 mx-5">
    <h2>Add Articles</h2>
</div>

<form method="post">
  
    {% csrf_token %}
    {% for field in form %}
    {{form.as_p}}
  {% endfor %}

<div class="form-group row mx-5">
    <button type="submit" class="btn btn-info btn-block">Submit</button>
</div>

</form>

enterpreneur_network/templates/Articles/articles_category.html
{% extends 'generic_base.html' %}

{% block content %}
<!-- Top picture start -->
<div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Others/images/93.jpg'); background-repeat: no-repeat; background-size: cover;">
    <!-- Mask & flexbox options-->
    <div class="mask rgba-black-light d-flex justify-content-center align-items-center">
      <!-- Content -->
      <div class="text-center white-text mx-5 wow fadeIn">
        <h1 class="mb-4">
          <strong>ARTICLES EXPERTS AND STORIES OF ENTERRPRENUERSHIP</strong>
        </h1>
        <p class="mb-4 d-none d-md-block">
          <strong>Great content to learn you about enterpreneurship.</strong>
        </p>
      </div>
      <!-- Content -->
    </div>
    <!-- Mask & flexbox options-->
</div>
  <!-- Top picture end -->

<div class="container mt-4">
  <!-- Category name -->
	<div class="alert alert-dark" role="alert" style="text-align: center;">
  {{name}}
  </div>
  <!-- Category name -->
	<div class="row mb-4 wow fadeIn">
    {% if Articles %}
        {% for article in Articles %}
          <!--Grid column-->
            <div class="col-lg-4 col-md-6 mb-4">
              <!--Card start-->
              <div class="card">
                <!--Card image start-->
                <div class="view overlay">
                  <!-- Article image -->
                  <img src="{{article.thumbnail.url}}" class="card-img-top" alt="" style="width: 100%; height: 12rem;">
                  <a href="{{article.get_absolute_url}}">
                    <div class="mask rgba-white-slight"></div>
                  </a>
                </div>
                <!-- Card image end -->
                <!--Card content start-->
                <div class="card-body">
                  <!-- Time -->
                  <p class="card-text">{{article.timestamp}} </p>
                  <!--Title-->
                  <h6 class="card-title">{{article}}</h6>
                </div>
              </div>
              <!--Card end-->
            </div>
          <!--Grid column-->
        {% endfor %}
    {% else %}
        <h4> There is no article of category {{name}} </h4>
    {% endif %}
  </div>
</div>

{% endblock %}

enterpreneur_network/templates/Articles/contact_us.html
{% extends 'generic_base.html' %}

{% block content %}
<main class="mt-5 pt-5">
  {% if email_status %}
    <div class=" container alert alert-info" role="alert">
      <h5 style="text-align: center;">{{email_status}}</h5>
    </div>  
  {% endif %}
<div class="container mt-5">
  <form action="{% url 'Articles:contact-us' %}" method="post">
    {% csrf_token %}
    <!-- Heading -->
    <h3 class="dark-grey-text text-center">
      <strong>CONTACT US</strong>
    </h3>
    <div class="md-form">
      <i class="fas fa-user prefix text-info "></i>
        <!-- input -->
        {{form.name}} 
        <!-- label -->
        {{form.name.label_tag}}
    </div>
    <div class="md-form">
      <i class="fas fa-envelope prefix text-info "></i>
        <!-- input -->
        {{form.email}}
        <!-- label -->
        {{form.email.label_tag}}
    </div>
    <div class="md-form">
      <i class="fas fa-pencil-alt text-info prefix"></i>
        <!-- input -->
        {{form.message}}
        <!-- label -->
        {{form.message.label_tag}}
    </div>
    <!-- button|send -->
    <div class="text-center">
      <button type="submit" class="btn btn-info">Send</button>
    </div>
  </form>
  <!-- Form -->
</div>
</main>
{% endblock %}